language: php

php:
  - 7.2

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
      
before_script:
  - cp .env.travis .env
  - mysql -u root -e "create database IF NOT EXISTS itsallwidgets;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON itsallwidgets.* To 'itsallwidgets'@'localhost' IDENTIFIED BY 'itsallwidgets'; FLUSH PRIVILEGES;"
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate

script:
  - php artisan key:generate
  - vendor/bin/phpunit tests/Feature/FlutterApp.php
