language: php

php:
  - 7.2

services:
  - mysql

before_script:
  - cp .env.travis .env
  - mysql -u root -e "create database IF NOT EXISTS itsallwidgets;"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON itsallwidgets.* To 'itsallwidgets'@'localhost' IDENTIFIED BY 'itsallwidgets'; FLUSH PRIVILEGES;"
  - composer self-update
  - composer install --no-interaction
  - php artisan migrate

script:
  - php artisan key:generate
  - vendor/bin/phpunit tests/Feature/FlutterApp.php

after_script:
  - cat storage/logs/laravel-error.log
  - cat storage/logs/laravel-info.log
#  - FILES=$(find tests/_output -type f -name '*.png' | sort -nr)
#  - for i in $FILES; do echo $i; base64 "$i"; break; done
